version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      DB_NAME:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - database-data:/var/lib/postgresql/data/

    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database-data:
